# PyLESA requirements yaml file for creating conda environments

name: PyLESA
channels:
  - conda-forge
  - defaults
  # - gurobi
dependencies:
  - matplotlib==3.1.3
  - numpy==1.22.0
  - scipy==1.4.1
  - pip

  - pip:
    - windpowerlib==0.2.1
    - progressbar33==2.4
    - scikit_learn==0.22.1
    - gekko==0.2.6
    - pvlib==0.7.2
    - pandas==1.5.1
    - openpyxl

